#include "cgem/generator_abi.h"

#include "cgem/core/allocator.h"
#include "cgem/core/attribute.h"
#include "cgem/core/attributes.h"
#include "cgem/core/node.h"
#include "cgem/core/writer.h"

#include <stdio.h>
#include <string.h>

static cgem_char_t *header_line = NULL;

static const cgem_char_t *attribute_string(cgem_node_t *node,
                                           const cgem_char_t *key)
{
    const cgem_attribute_t *attribute =
        cgem_attributes_find(cgem_node_get_attributes(node), key);

    if (!attribute) {
        return NULL;
    }
    return cgem_attribute_value_get_string(cgem_attribute_get_value(attribute));
}

static cgem_bool_t write_line(cgem_writer_t *writer, const cgem_char_t *text)
{
    return cgem_writer_write(writer, text, strlen(text));
}

static cgem_bool_t generate_default(cgem_node_t *root,
                                    cgem_generator_sink_t *sink,
                                    cgem_char_t *error, size_t error_size)
{
    cgem_writer_t *writer;
    size_t count;
    size_t i;
    cgem_bool_t ok = true;

    if (!root || !sink) {
        snprintf(error, error_size, "example generator: missing root or sink");
        return false;
    }
    if (!header_line) {
        snprintf(error, error_size, "example generator: not initialized");
        return false;
    }
    writer = cgem_generator_sink_open(sink, "example.txt", error, error_size);
    if (!writer) {
        return false;
    }
    if (!write_line(writer, header_line)) {
        snprintf(error, error_size, "example generator: write failed");
        cgem_writer_free(writer);
        return false;
    }
    count = cgem_node_get_count(root);
    for (i = 0; i < count && ok; i++) {
        cgem_node_t *child = cgem_node_get(root, i);
        const cgem_char_t *name = attribute_string(child, "name");
        const cgem_char_t *type = attribute_string(child, "type");
        cgem_char_t line[256];

        snprintf(line, sizeof(line), "// %s: %s\n", type ? type : "node",
                 name ? name : "(unnamed)");
        if (!write_line(writer, line)) {
            snprintf(error, error_size, "example generator: write failed");
            ok = false;
        }
    }
    cgem_writer_free(writer);
    return ok;
}

static cgem_bool_t init(cgem_generator_registrar_t *registrar,
                        const cgem_attributes_t *config, cgem_char_t *error,
                        size_t error_size)
{
    static const cgem_char_t text[] = "// generated by example\n";

    (void) config;

    header_line = cgem_alloc(sizeof(text));
    if (!header_line) {
        snprintf(error, error_size, "example generator: out of memory in init");
        return false;
    }
    memcpy(header_line, text, sizeof(text));

    if (!cgem_generator_registrar_add_attribute_key(registrar, "name") ||
        !cgem_generator_registrar_add_attribute_key(registrar, "type") ||
        !cgem_generator_registrar_add_target(registrar, "default",
                                             generate_default)) {
        snprintf(error, error_size, "example generator: registration failed");
        cgem_free(header_line);
        header_line = NULL;
        return false;
    }
    return true;
}

static void deinit(void)
{
    cgem_free(header_line);
    header_line = NULL;
}

static const cgem_generator_vtable_t vtable = {
    CGEM_GENERATOR_ABI_VERSION,
    "example",
    init,
    deinit
};

const cgem_generator_vtable_t *cgem_generator_get_vtable(void)
{
    return &vtable;
}
