#include "cgem/generator_abi.h"

#include "cgem/core/allocator.h"
#include "cgem/core/attribute.h"
#include "cgem/core/attributes.h"
#include "cgem/core/node.h"
#include "cgem/core/writer.h"

#include <stdio.h>
#include <string.h>

static char *header_line = NULL;

static const char *attribute_string(cgem_node_t *node, const char *key)
{
    const cgem_attribute_t *attribute =
        cgem_attributes_find(cgem_node_get_attributes(node), key);

    if (!attribute) {
        return NULL;
    }
    return cgem_attribute_value_get_string(cgem_attribute_get_value(attribute));
}

static bool write_line(cgem_writer_t *writer, const char *text)
{
    return cgem_writer_write(writer, text, strlen(text));
}

static bool generate_default(cgem_node_t *root, cgem_writer_t *writer,
                             char *error, size_t error_size)
{
    size_t count;
    size_t i;

    if (!root || !writer) {
        snprintf(error, error_size, "example generator: missing root or writer");
        return false;
    }
    if (!header_line) {
        snprintf(error, error_size, "example generator: not initialized");
        return false;
    }
    if (!write_line(writer, header_line)) {
        snprintf(error, error_size, "example generator: write failed");
        return false;
    }
    count = cgem_node_get_count(root);
    for (i = 0; i < count; i++) {
        cgem_node_t *child = cgem_node_get(root, i);
        const char *name = attribute_string(child, "name");
        const char *type = attribute_string(child, "type");
        char line[256];

        snprintf(line, sizeof(line), "// %s: %s\n", type ? type : "node",
                 name ? name : "(unnamed)");
        if (!write_line(writer, line)) {
            snprintf(error, error_size, "example generator: write failed");
            return false;
        }
    }
    return true;
}

static bool init(cgem_generator_registrar_t *registrar, char *error,
                 size_t error_size)
{
    static const char text[] = "// generated by example\n";

    header_line = cgem_alloc(sizeof(text));
    if (!header_line) {
        snprintf(error, error_size, "example generator: out of memory in init");
        return false;
    }
    memcpy(header_line, text, sizeof(text));

    if (!cgem_generator_registrar_add_attribute_key(registrar, "name") ||
        !cgem_generator_registrar_add_attribute_key(registrar, "type") ||
        !cgem_generator_registrar_add_target(registrar, "default",
                                             generate_default)) {
        snprintf(error, error_size, "example generator: registration failed");
        cgem_free(header_line);
        header_line = NULL;
        return false;
    }
    return true;
}

static void deinit(void)
{
    cgem_free(header_line);
    header_line = NULL;
}

static const cgem_generator_vtable_t vtable = {
    CGEM_GENERATOR_ABI_VERSION,
    "example",
    init,
    deinit
};

const cgem_generator_vtable_t *cgem_generator_get_vtable(void)
{
    return &vtable;
}
